### ISSUE TITLE
I can only deploy one secret contract on the network

### ISSUE THREAD

**Issue by lacabra** [scrtlabs/enigma-core#113]
**Describe the bug**
I have multiple valid secret contracts that I can successfully deploy if I restart the network every time. However, once I have successfully deployed a contract on the network, any subsequent attempt to deploy any other contract (that would otherwise succeed if it was the first one), will fail with the following error:

```
core_1        | Error in deployment of smart contract function: Input Error: Cryptography Error: DecryptionError
core_1        | 06:38:16 [INFO] LOG DERIVE: Ok(FailedTask { result: FailedTask { output: "92ffb22994188d60a9538bbe0d9d3065de055abd524176d5ca339c1bab87c31ec39ba4856c76cefc6863655f6594df70848b615fcc7c1a5c542abb698f475319c2582a4fcb659ab3d59bb716", used_gas: 0, signature: "ec455b1f3f83b54d02b25c1e8f84154f68360860afcea5ed7f5fb7ba9370d0e4002fdd37b432374fb7760323bc7815ec7e08eaae20d6a259967c72521b7f41281b" } })
core_1        | building state for 1 contracts
```

**To Reproduce**
Deploy two different contracts consecutively.

**Expected behavior**
Should be able to deploy more than one contract on the network.

**Comment by elichai** [comment]
Are you making sure that core has the state keys? (using PTT)

**Comment by lacabra** [comment]
See my answer to #114, as I believe it also applies here: I only control the client library, and it is not the responsibility of the client to manage the keys. I do confirm that the PTT works as expected when an epoch changes, but P2P probably does not trigger a new PTT request for the new contract (Cc: @lenak25)

**Comment by lacabra** [comment]
I had misidentified this problem as something else. The underlying issue is that P2P does not request the state keys prior to passing the deployment task to core, so I'm closing this issue in favor of [this other one](https://github.com/enigmampc/enigma-p2p/issues/136) in P2P.
