### ISSUE TITLE
Inconsistent Message Signing

### ISSUE THREAD

**Issue by lacabra** [scrtlabs/enigma-core#115]
Please adjust [this function](https://github.com/enigmampc/enigma-core/blob/904c1b4dc3646ad83eb6ed20030b073b2e4acbc6/enigma-core/app/cross-test-utils/src/lib.rs#L33) to match the signing standard that we have adopted of prepending the length to each variable in the message, otherwise matching signatures across the codebase becomes a nightmare.

Thank you 🙏

**Comment by AvishaiW** [comment]
fixed in #116
