### ISSUE TITLE
Deploy/Compute with wrong parameters fails due to Out of Gas

### ISSUE THREAD

**Issue by lacabra** [scrtlabs/enigma-core#117]
**Describe the bug**

This may be more of a question than a bug, but running a deploy or compute with the wrong set of parameters fails due to an out of gas, with the following message:
```
Error in execution of smart contract function: Invocation resulted in gas limit violated
```

Is there a way we can distinguish this case from a when the execution fails because of out of gas when the gas is too low?

**To Reproduce**
Run the following integration tests in order:
1. `01_init.spec.js`
2. `02_deploy_calculator.spec.js`
3. `10_execute_calculator.spec.js` <- not strictly necessary, but you will see how a `mul()`computation will consume about `26956` gas
4.  `03_deploy_fail_parameters.spec.js` fails because out of gas, even when the gas limit is set much higher (at `1,000,000`) than what a successful compute with the correct parameters will take for the same `mul()` operation.

**Expected behavior**

I would expect a different error that would help me tell them apart.

**Comment by elichai** [comment]
What do you mean by "Wrong set of parameters"?

**Comment by lacabra** [comment]
I mean a set of parameters that does not match the function definition. In the test mentioned above, I try to compute “mul(a,b)” to multiply two numbers, and I only pass one of the two numbers as a parameter.

In other languages I would get an error like wrong number of parameters, but here I get an out of gas error.

**Comment by moriaab** [comment]
@lacabra 
I cannot reproduce this defect in core. If the parameters don't match the function definition, there is an exception, but not gas limit. I suggest during the integration test to print in core what is the gas limit that the core got.

**Comment by moriaab** [comment]
The reason for "out of gas" exception was insufficient amount of gas, which is normal. For the exception caused by "Wrong set of parameters" the different issue will be opened.
