### ISSUE TITLE
Align `GetContract` IPC message to P2P

### ISSUE THREAD

**Issue by lenak25** [scrtlabs/enigma-core#161]
As defined at [P2P PR](https://github.com/enigmampc/enigma-p2p/pull/197)

**Comment by elichai** [comment]
@AvishaiW it's basically to add the contract address to the `GetContract` response.
you would need to change this https://github.com/enigmampc/enigma-core/blob/develop/enigma-core/app/src/networking/messages.rs#L55 to a struct-like variant renamed `result` with both `bytecode` and `address` and then adjust the return value in the `handle_messages` module.
