### ISSUE TITLE
Move  code output from verbosity level 2 to 3

### ISSUE THREAD

**Issue by lacabra** [scrtlabs/enigma-core#177]
**Is your feature request related to a problem? Please describe.**
When running the the integration integration test on Travis (and trying to integrate the integration tests with other repos on Travis), Travis reports [Log Length exceeded](https://docs.travis-ci.com/user/common-build-problems/#log-length-exceeded) and aborts before the tests finish.

In the current setup core runs with `-vv`. If I change the verbosity level to `-v` the tests succeed, but I don't have enough visibility to what core does to be able to troubleshoot.

**Describe the solution you'd like**
When you choose verbosity level 2 with `-vv`, when deploying a contract (message `Ok(DeploySecretContract...)` would not include the `output` field that contains the bytecode of the deployed contract, but would include all other fields.

The, to display the field above with all others, you would choose `-vvv`.

**Comment by lacabra** [comment]
I have been thinking this more thoroughly, and I would like to amend my request as follows:

- Include the output of deploy and computations in verbosity level 1: `-v` without the `output` bytecode. This is the most useful output for debugging purposes most of the time.
- Leave verbosity level 2: `-vv` as is.

The rationale is that the rest of stuff that is logged on level 2, clutters the CI and is not that useful when I only need to know whether deploy/computation succeeds, so I would only like to see that in level 1 for the CI, and when I run it manually I can choose level 2 and see everything that I'm seeing now.

**Comment by moriaab** [comment]
@lacabra 
1. In this issue, do you mean stdout logs only?
2. As far as I understand, you want that there will be:
   - some verbosity level **L** that includes output of deploy and computations **without bytecode**
   - the next verbosity level **L+1** that includes output of deploy and computations **with bytecode**
3. I agree with the request, but I am not sure that `L` should be `-v`. In core the levels of the debug are compatible with the Rust log package and defined as follows:
        0  - off,
        1  - error,
        2  - warn,
        3 - info,
        4 - debug,
        5 and more - trace
In addition, in core the log level of stdout is the level defined by a user+1 (the reason for that was that even with no verbose, errors will be printed to stdout). Therefore, `-v`means *warn* level. I think that `L` level should be at least *info*.

**Comment by moriaab** [comment]
@lacabra 
I merged the change. Please see if the issue can be closed.

**Comment by lacabra** [comment]
I confirm that this has been resolved in #179. Thank you!
