### ISSUE TITLE
Possible typo in array initialization in erc20 secret contract example

### ISSUE THREAD

**Issue by lauracw100** [scrtlabs/enigma-core#228]
**Describe the bug**
Referencing `dev-help` issue: https://github.com/enigmampc/dev-help/issues/9

User encountered a decryption error during enclave execution which was narrowed down to the line:

`let mut new_sig: [u8; 65] = [0u8; 65];`

that he copied from the `verify()` method here: `enigma-core/examples/eng_wasm_contracts/erc20/src/lib.rs`

It looks like a typo with the `0u8` instead of `0`, but I'm not sure. I can't find any examples of initializing an array in Rust that way, but _rustc_ doesn't complain about it.

**To Reproduce**
1. Use erc20 example SC as a base to create a test SC
2. Include the `verify()` function
3. Compile, migrate and deploy
4. Write a test to call the verify function

**Expected behavior**
No decryption error

**Backtrace**
```
contract_1  | eth_call
core_1      | Error in deployment of smart contract function: Input Error: Cryptography Error: DecryptionError
core_1      | 13:14:25 [INFO] Ok(FailedTask { result: FailedTask { output: "6bc1fc2006c30f2df0ab7057c8d0d45470f2fec85b3ca1c31a0a371fc8d5c58333a476edd7306715f65baeb7f9c4f183024b81e1dea0f741e9661e3eadf2a8263ce21deee17f28f9413fef9a", used_gas: 0, signature: "d789928aff806eb8c91357b112cef81529f0edd384fb30eed68ae87362cc857f6368734d725e1646e07482b7c2d9c4078049bb9a312afd845c8c6b97b2d73b881c" } })
core_1      | building state for 8 contracts
```

**Comment by AvishaiW** [comment]
@lauraweindorf sorry for the late response. 
The `verify()` function is a private function of the contract and cannot be called from outside. the methods that can be called from outside are ones that are included in the `Erc20Interface` trait. therefore, it wasn't able to decrypt your request.
Hope this helps.

**Comment by AvishaiW** [comment]
@lauraweindorf sorry for the late response.
The `verify()` function is a private function and cannot be called from the outside. methods from the `Erc20Interface` trait are the only ones that can be called from the outside, therefore, it wasn't able to decrypt your request.
Hope this helps.

**Comment by lauracw100** [comment]
Hi @AvishaiW 

I just reviewed his code again. It's calling the private `verify()` function from his `Erc20Interface` impl's public function `join_game` as: 
```
fn join_game(game_id: U256, pub_key: H256, move_2: String, sig: Vec<u8>) {
        let hash = encode(Hash::Keccak256, &move_2.as_bytes()).unwrap();
        assert!(Self::verify(pub_key, hash, sig));
```

It seems to be the same way it's done in `enigma-core/examples/eng_wasm_contracts/erc20/src/lib.rs`, where the private `verify()` function is called from the `ContractInferface` impl's public function `mint` as:
```
 fn mint(owner: H256, addr: H256, tokens: U256, sig: Vec<u8>) {
        // verify the owner is the one who is minting.
        let contract_owner: H256 = read_state!(CONTRACT_OWNER).unwrap();
        assert_eq!(owner, contract_owner);
        assert!(Self::verify(owner, addr, tokens, sig));
```
In both cases the private function is being called from the trait implementation's public function as `Self::verify()`. 

Just checking because he said he copied from the example code?

**Comment by AvishaiW** [comment]
Hey @lauraweindorf,
I think I'm still missing some information.
from my understanding and from looking at [this repo](https://github.com/PeterMPhillips/discovery_rock_paper_scissors) `verify` is called from a function from within the SC, which seems to be ok. 
Is it possible to get the code which creates the signature which is passed into the secret contract, because the SC itself seems to be fine?
Thanks!

**Comment by lauracw100** [comment]
Sorry for the delay, @AvishaiW! I'll see if I can get that info for you. Meanwhile, what do you think of that array definition/initialization:

`let mut new_sig: [u8; 65] = [0u8; 65];`  

instead of:

`let mut new_sig: [u8; 65] = [u8; 65];`

The former is the way it's setup in this example secret contract:

`enigma-core/examples/eng_wasm_contracts/erc20/src/lib.rs`

Peter had copied from there and built his code using that as a base. I did notice that when I corrected that statement, his issue was resolved.

Thanks for looking into this!

**Comment by AvishaiW** [comment]
That's strange that it fixed his issue. From my understanding that is a sufficient way of writing in rust as you can see here: https://stackoverflow.com/questions/53120755/what-does-0u8-mean-in-rust, what do you say?

**Comment by lauracw100** [comment]
oh you're right. I wonder if there's a difference between using that notation with array initialization vs a statement initializing a non-array type?

**Comment by AvishaiW** [comment]
Hope this answers your question: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=23563c7e97891df1f37d7925df938481

**Comment by lauracw100** [comment]
okay, yeah that answers it. Thanks @AvishaiW!

Do you still want the code that creates the signature which is passed into his secret contract? Or should we just close this issue?
