### ISSUE TITLE
cargo test -- --ignored  failed

### ISSUE THREAD

**Issue by 60ke** [scrtlabs/enigma-core#233]
test evm_u::evm::tests::bill_encrypted ... FAILED
test evm_u::evm::tests::bill_with_bool ... FAILED
test evm_u::evm::tests::mix_addresses ... FAILED
test evm_u::evm::tests::bill ... FAILED

**Comment by AvishaiW** [comment]
@60ke We don't support EVM at the moment, therefore we are ignoring the tests.

**Comment by moriaab** [comment]
@60ke We removed evm code and tests.
